### ISSUE TITLE
\

### ISSUE THREAD

**Issue by abajaj945** [voxel51/pandemic51#105]

**Comment by benjaminpkane** [comment]
Hi @abajaj945, it looks like this was already resolved by you, but a template config is provided [here](https://github.com/voxel51/pandemic51/blob/develop/config/config-template.py).

Per the [README](https://github.com/voxel51/pandemic51#environment-variables-and-configuration) instructions, you can copy that template into the package's base directory.
```sh
cp config/config-template.py pandemic51/config.py
```

Thanks for you interest!
