### ISSUE TITLE
Call to action buttons have unequal widths on mobile

### ISSUE THREAD

**Issue by brimoor** [voxel51/pandemic51#53]
The `Contact us` and `Contribute` buttons have unequal widths on mobile.

They should either be:
(a) both full width, like `Contribute` below
(b) both equal width, separate lines, and centered
(c) narrow and on the same line

I vote for (a).

![IMG_F20C2B29CF2A-1](https://user-images.githubusercontent.com/25985824/77984093-a7199800-72de-11ea-8788-2779b9a0ab50.jpeg)

**Comment by benjaminpkane** [comment]
Resolved by https://github.com/voxel51/pandemic51/pull/54/commits/b9a1d6d59432460e4fdf2a75e4065a53ef89c9c9

![screenshot-localhost-9001-1585661463475](https://user-images.githubusercontent.com/19821840/78032050-66e40500-7332-11ea-99e5-a494c38132d6.png)

**Comment by benjaminpkane** [comment]
![screenshot-localhost-9001-1585661510727](https://user-images.githubusercontent.com/19821840/78032089-77947b00-7332-11ea-8603-dafa6a32e2ac.png)
