### ISSUE TITLE
Contact us button too big on web

### ISSUE THREAD

**Issue by brimoor** [voxel51/pandemic51#55]
<img width="789" alt="Screen Shot 2020-03-31 at 9 20 57 AM" src="https://user-images.githubusercontent.com/25985824/78031075-04d6d000-7331-11ea-83b3-abc0eb8dc314.png">

**Comment by benjaminpkane** [comment]
Resolved by https://github.com/voxel51/pandemic51/pull/54/commits/b9a1d6d59432460e4fdf2a75e4065a53ef89c9c9

![screenshot-localhost-9001-1585661463475](https://user-images.githubusercontent.com/19821840/78032114-824f1000-7332-11ea-8d2e-e1490cb112f0.png)
