### ISSUE TITLE
"Touch" should be "click" on web

### ISSUE THREAD

**Issue by brimoor** [voxel51/pandemic51#56]
<img width="476" alt="Screen Shot 2020-03-31 at 9 25 46 AM" src="https://user-images.githubusercontent.com/25985824/78031536-acec9900-7331-11ea-8caf-4b92559bf454.png">

**Comment by benjaminpkane** [comment]
Resolved by https://github.com/voxel51/pandemic51/pull/54/commits/33643a1352730212150c6cd7234762f8cce059a9

![screenshot-localhost-9001-1585661392241](https://user-images.githubusercontent.com/19821840/78031910-313f1c00-7332-11ea-92bd-7a7f75e4e777.png)
